
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sns?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true
    username: sns
    password: sns-pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

