version: "3.7"
services:
  sns-db:
    image: mysql:8.1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=sns
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=sns
      - MYSQL_PASSWORD=sns-pass
      - TZ=UTC
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./mysql:/var/lib/mysql